blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('',PostListView.as_view(), name='blog-home'),
    path('post/<int:pk>/',PostDetailView.as_view(), name='blog-single'),
    path('post-create/',PostCreateView.as_view(), name='post-create'),
    path('post-update/<int:pk>/',PostUpdateView.as_view(), name='post-update'),
    path('post-delete/<int:pk>/',PostDeleteView.as_view(), name='post-delete'),
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser,BaseUserManager,PermissionsMixin)
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class UserManager(BaseUserManager):
    '''
    Custom user model manager
    '''
    def create_user(self,email,password,**extra_fields):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(email=self.normalize_email(email),**extra_fields)
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self,email,password,**extra_fields):
        extra_fields.setdefault('is_staff',True)
        extra_fields.setdefault('is_superuser',True)
        extra_fields.setdefault('is_active',True)
        user = self.create_user(email,password)
        user.is_staff = True
        user.is_superuser = True
        user.save()
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        
        return self.create_superuser(email,password,**extra_fields)
    

class User(AbstractBaseUser, PermissionsMixin):
    '''
    Custom user model
    '''
    email = models.EmailField(unique=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    USERNAME_FIELD = 'email'
    manager = UserManager()

    def __str__(self):
        return self.email


class Profile(models.Model):
    '''
    profile model
    '''
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    username = models.CharField(max_length=255)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    image = models.ImageField(null=True,blank=True)
    description = models.TextField(null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email
    

@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

blog/models.py
from django.db import models


from django.contrib.auth import get_user_model
User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']


class Post(models.Model):
    '''
    this is the model for post in blog application
    '''
    image = models.ImageField(upload_to='blog', default='default.jpg')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    status = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(null=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_date']

blog/forms.py
from django import forms
from .models import Post


class PostCreateForm(forms.ModelForm):

    class Meta:
        model= Post
        fields = ['title','content','category']

accounts/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.views.generic import (
    TemplateView, RedirectView , ListView, DetailView, FormView, CreateView, UpdateView,DeleteView
)
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import Post
from .forms import PostCreateForm

    
class RedirectToBlog(RedirectView):
    url = '/blog/'
    
    
class PostListView(PermissionRequiredMixin,ListView):
    permission_required = ["blog.view_post"]
    queryset = Post.objects.filter(status=True)
    context_object_name = 'posts'
    paginate_by = 4
    ordering = 'id'  
    
    
class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'


#class PostCreateView(FormView):
#    template_name = "home/create_post.html"
#    form_class = PostCreateForm
#    success_url = "/blog/"#

#    def form_valid(self, form):
#        form.save()
#        return super().form_valid(form)#

class PostCreateView(CreateView):
    model = Post
    #fields = ['author','title','content','status','category','published_date']
    form_class = PostCreateForm
    template_name = "home/create_post.html"
    success_url = "/blog/"
    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.status = False
        form.instance.published_date =None
        return super().form_valid(form)
    
class PostUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content']
    template_name = "blog/update_post.html"
    success_url = "/blog/"


class PostDeleteView(DeleteView):
    model = Post
    template_name = "blog/delete_post.html"
    success_url = "/blog/"

templates/blog/delete_post.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
            <form method="post">
                 {% csrf_token %}
                 <p>Are you sure you want to delete</p>
                 {{form}}
                 <button type="submit">Delete</button>
            </form>
    </body>
</html>

templates/blog/post_detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
            {{post.title}}
    </body>
</html>

templates/blog/post_list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {% for post in posts %}
            <h3><a href="{% url 'blog:blog-single' pk=post.id %}">{{post.title}}</a></h3>
            <a href="{% url 'blog:post-update' pk=post.id %}">update</a>
            <a href="{% url 'blog:post-delete' pk=post.id %}">delete</a>
        {% endfor %}
        <a href="{% url 'blog:post-create' %}">create post</a>


        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
        {% endif %}
        {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Next Page</a>
        {% endif %}
    </body>
</html>

templates/blog/update_post.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
            <form method="post">
                 {% csrf_token %}
                 {{form.as_p}}
                 <button type="submit">Update</button>
            </form>
    </body>
</html>

templates/home/create_post.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
            <form method='post'>
                {% csrf_token %}
                {{form.as_p}}
                <button type='submit'>send</button>
            </form>
    </body>
</html>